//! # Trident Generated Types
//!
//! This file is automatically generated by Trident.
//! **DO NOT EDIT THIS FILE MANUALLY**

#![allow(dead_code)]
#![allow(unused_imports)]

use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use trident_fuzz::fuzzing::*;

// ============================================================================
// PROGRAM MODULES
// ============================================================================

// ----------------------------------------------------------------------------
// Program: solnadocash
// ----------------------------------------------------------------------------
pub mod solnadocash {
    use super::*;

    // ------------------------------------------------------------------------
    // Program ID
    // ------------------------------------------------------------------------

    /// Returns the program ID for solnadocash
    pub fn program_id() -> Pubkey {
        pubkey!("DMAPWBXb5w2KZkML2SyV2CtZDfbwNKqkWL3scQKXUF59")
    }

    // ------------------------------------------------------------------------
    // Instructions
    // ------------------------------------------------------------------------

    // ....................................................................
    // Instruction: Deposit
    // ....................................................................

    /// Main instruction struct for Deposit
    pub struct DepositInstruction {
        pub accounts: DepositInstructionAccountMetas,
        pub data: DepositInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Deposit instruction
    #[derive(Debug, Clone, Default)]
    pub struct DepositInstructionAccountMetas {
        pub pool: AccountMeta,

        pub vault: AccountMeta,

        pub depositor: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for Deposit instruction
    #[derive(Debug, Clone)]
    pub struct DepositInstructionAccounts {
        pub pool: Pubkey,

        pub vault: Pubkey,

        pub depositor: Pubkey,
    }

    impl DepositInstructionAccounts {
        pub fn new(pool: Pubkey, vault: Pubkey, depositor: Pubkey) -> Self {
            Self {
                pool,

                vault,

                depositor,
            }
        }
    }

    /// Instruction data for Deposit
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct DepositInstructionData {
        pub commitment: [u8; 32],
    }

    impl DepositInstructionData {
        pub fn new(commitment: [u8; 32]) -> Self {
            Self { commitment }
        }
    }

    /// Implementation for DepositInstruction
    impl DepositInstruction {
        fn discriminator() -> [u8; 8] {
            [242u8, 35u8, 198u8, 137u8, 82u8, 225u8, 242u8, 182u8]
        }

        pub fn data(data: DepositInstructionData) -> Self {
            Self {
                accounts: DepositInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: DepositInstructionAccounts) -> Self {
            self.accounts.pool = AccountMeta::new(accounts.pool, false);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self.accounts.depositor = AccountMeta::new(accounts.depositor, true);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.pool.clone());

            metas.push(self.accounts.vault.clone());

            metas.push(self.accounts.depositor.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: InitializePool
    // ....................................................................

    /// Main instruction struct for InitializePool
    pub struct InitializePoolInstruction {
        pub accounts: InitializePoolInstructionAccountMetas,
        pub data: InitializePoolInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for InitializePool instruction
    #[derive(Debug, Clone, Default)]
    pub struct InitializePoolInstructionAccountMetas {
        pub admin: AccountMeta,

        pub pool: AccountMeta,

        pub vault: AccountMeta,

        pub treasury: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for InitializePool instruction
    #[derive(Debug, Clone)]
    pub struct InitializePoolInstructionAccounts {
        pub admin: Pubkey,

        pub pool: Pubkey,

        pub vault: Pubkey,

        pub treasury: Pubkey,
    }

    impl InitializePoolInstructionAccounts {
        pub fn new(admin: Pubkey, pool: Pubkey, vault: Pubkey, treasury: Pubkey) -> Self {
            Self {
                admin,

                pool,

                vault,

                treasury,
            }
        }
    }

    /// Instruction data for InitializePool
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct InitializePoolInstructionData {
        pub denomination: u64,

        pub version: u8,
    }

    impl InitializePoolInstructionData {
        pub fn new(denomination: u64, version: u8) -> Self {
            Self {
                denomination,

                version,
            }
        }
    }

    /// Implementation for InitializePoolInstruction
    impl InitializePoolInstruction {
        fn discriminator() -> [u8; 8] {
            [95u8, 180u8, 10u8, 172u8, 84u8, 174u8, 232u8, 40u8]
        }

        pub fn data(data: InitializePoolInstructionData) -> Self {
            Self {
                accounts: InitializePoolInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: InitializePoolInstructionAccounts) -> Self {
            self.accounts.admin = AccountMeta::new(accounts.admin, true);

            self.accounts.pool = AccountMeta::new(accounts.pool, false);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self.accounts.treasury = AccountMeta::new_readonly(accounts.treasury, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.admin.clone());

            metas.push(self.accounts.pool.clone());

            metas.push(self.accounts.vault.clone());

            metas.push(self.accounts.treasury.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: PausePool
    // ....................................................................

    /// Main instruction struct for PausePool
    pub struct PausePoolInstruction {
        pub accounts: PausePoolInstructionAccountMetas,
        pub data: PausePoolInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for PausePool instruction
    #[derive(Debug, Clone, Default)]
    pub struct PausePoolInstructionAccountMetas {
        pub admin: AccountMeta,

        pub pool: AccountMeta,
    }

    /// Account pubkeys for PausePool instruction
    #[derive(Debug, Clone)]
    pub struct PausePoolInstructionAccounts {
        pub admin: Pubkey,

        pub pool: Pubkey,
    }

    impl PausePoolInstructionAccounts {
        pub fn new(admin: Pubkey, pool: Pubkey) -> Self {
            Self { admin, pool }
        }
    }

    /// Instruction data for PausePool
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct PausePoolInstructionData {}

    impl PausePoolInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for PausePoolInstruction
    impl PausePoolInstruction {
        fn discriminator() -> [u8; 8] {
            [160u8, 15u8, 12u8, 189u8, 160u8, 0u8, 243u8, 245u8]
        }

        pub fn data(data: PausePoolInstructionData) -> Self {
            Self {
                accounts: PausePoolInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: PausePoolInstructionAccounts) -> Self {
            self.accounts.admin = AccountMeta::new_readonly(accounts.admin, true);

            self.accounts.pool = AccountMeta::new(accounts.pool, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.admin.clone());

            metas.push(self.accounts.pool.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: UnpausePool
    // ....................................................................

    /// Main instruction struct for UnpausePool
    pub struct UnpausePoolInstruction {
        pub accounts: UnpausePoolInstructionAccountMetas,
        pub data: UnpausePoolInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for UnpausePool instruction
    #[derive(Debug, Clone, Default)]
    pub struct UnpausePoolInstructionAccountMetas {
        pub admin: AccountMeta,

        pub pool: AccountMeta,
    }

    /// Account pubkeys for UnpausePool instruction
    #[derive(Debug, Clone)]
    pub struct UnpausePoolInstructionAccounts {
        pub admin: Pubkey,

        pub pool: Pubkey,
    }

    impl UnpausePoolInstructionAccounts {
        pub fn new(admin: Pubkey, pool: Pubkey) -> Self {
            Self { admin, pool }
        }
    }

    /// Instruction data for UnpausePool
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct UnpausePoolInstructionData {}

    impl UnpausePoolInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for UnpausePoolInstruction
    impl UnpausePoolInstruction {
        fn discriminator() -> [u8; 8] {
            [241u8, 148u8, 129u8, 243u8, 222u8, 125u8, 125u8, 160u8]
        }

        pub fn data(data: UnpausePoolInstructionData) -> Self {
            Self {
                accounts: UnpausePoolInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: UnpausePoolInstructionAccounts) -> Self {
            self.accounts.admin = AccountMeta::new_readonly(accounts.admin, true);

            self.accounts.pool = AccountMeta::new(accounts.pool, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.admin.clone());

            metas.push(self.accounts.pool.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Withdraw
    // ....................................................................

    /// Main instruction struct for Withdraw
    pub struct WithdrawInstruction {
        pub accounts: WithdrawInstructionAccountMetas,
        pub data: WithdrawInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Withdraw instruction
    #[derive(Debug, Clone, Default)]
    pub struct WithdrawInstructionAccountMetas {
        pub pool: AccountMeta,

        pub vault: AccountMeta,

        pub nullifier_pda: AccountMeta,

        pub recipient: AccountMeta,

        pub treasury: AccountMeta,

        pub relayer: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for Withdraw instruction
    #[derive(Debug, Clone)]
    pub struct WithdrawInstructionAccounts {
        pub pool: Pubkey,

        pub vault: Pubkey,

        pub nullifier_pda: Pubkey,

        pub recipient: Pubkey,

        pub treasury: Pubkey,

        pub relayer: Pubkey,
    }

    impl WithdrawInstructionAccounts {
        pub fn new(
            pool: Pubkey,

            vault: Pubkey,

            nullifier_pda: Pubkey,

            recipient: Pubkey,

            treasury: Pubkey,

            relayer: Pubkey,
        ) -> Self {
            Self {
                pool,

                vault,

                nullifier_pda,

                recipient,

                treasury,

                relayer,
            }
        }
    }

    /// Instruction data for Withdraw
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct WithdrawInstructionData {
        pub args: WithdrawArgs,
    }

    impl WithdrawInstructionData {
        pub fn new(args: WithdrawArgs) -> Self {
            Self { args }
        }
    }

    /// Implementation for WithdrawInstruction
    impl WithdrawInstruction {
        fn discriminator() -> [u8; 8] {
            [183u8, 18u8, 70u8, 156u8, 148u8, 109u8, 161u8, 34u8]
        }

        pub fn data(data: WithdrawInstructionData) -> Self {
            Self {
                accounts: WithdrawInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: WithdrawInstructionAccounts) -> Self {
            self.accounts.pool = AccountMeta::new(accounts.pool, false);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self.accounts.nullifier_pda = AccountMeta::new(accounts.nullifier_pda, false);

            self.accounts.recipient = AccountMeta::new(accounts.recipient, false);

            self.accounts.treasury = AccountMeta::new(accounts.treasury, false);

            self.accounts.relayer = AccountMeta::new(accounts.relayer, true);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.pool.clone());

            metas.push(self.accounts.vault.clone());

            metas.push(self.accounts.nullifier_pda.clone());

            metas.push(self.accounts.recipient.clone());

            metas.push(self.accounts.treasury.clone());

            metas.push(self.accounts.relayer.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ------------------------------------------------------------------------
    // Composite Accounts
    // ------------------------------------------------------------------------
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

/// Custom struct: DepositEvent
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct DepositEvent {
    pub leaf: [u8; 32],

    pub leaf_index: u64,

    pub timestamp: i64,
}

impl DepositEvent {
    pub fn new(leaf: [u8; 32], leaf_index: u64, timestamp: i64) -> Self {
        Self {
            leaf,

            leaf_index,

            timestamp,
        }
    }
}

/// Custom struct: Pool
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct Pool {
    pub admin: Pubkey,

    pub mint: Pubkey,

    pub denomination: u64,

    pub mint_decimals: u8,

    pub _pad0: [u8; 7],

    pub next_index: u64,

    pub treasury: Pubkey,

    pub version: u8,

    pub bump: u8,

    pub vault_bump: u8,

    pub is_paused: u8,

    pub _pad1: [u8; 4],

    pub current_root_index: u64,

    pub root_history: [[u8; 32]; 256],

    pub filled_subtrees: [[u8; 32]; 20],
}

impl Pool {
    pub fn new(
        admin: Pubkey,

        mint: Pubkey,

        denomination: u64,

        mint_decimals: u8,

        _pad0: [u8; 7],

        next_index: u64,

        treasury: Pubkey,

        version: u8,

        bump: u8,

        vault_bump: u8,

        is_paused: u8,

        _pad1: [u8; 4],

        current_root_index: u64,

        root_history: [[u8; 32]; 256],

        filled_subtrees: [[u8; 32]; 20],
    ) -> Self {
        Self {
            admin,

            mint,

            denomination,

            mint_decimals,

            _pad0,

            next_index,

            treasury,

            version,

            bump,

            vault_bump,

            is_paused,

            _pad1,

            current_root_index,

            root_history,

            filled_subtrees,
        }
    }
}

/// Custom struct: PoolNearSaturation
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct PoolNearSaturation {
    pub pool: Pubkey,

    pub next_index: u64,
}

impl PoolNearSaturation {
    pub fn new(pool: Pubkey, next_index: u64) -> Self {
        Self { pool, next_index }
    }
}

/// Custom struct: VaultAccount
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct VaultAccount {}

impl VaultAccount {
    pub fn new() -> Self {
        Self {}
    }
}

/// Custom struct: WithdrawArgs
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct WithdrawArgs {
    pub proof_a: [u8; 64],

    pub proof_b: [u8; 128],

    pub proof_c: [u8; 64],

    pub nullifier_hash: [u8; 32],

    pub root: [u8; 32],

    pub withdrawal_commitment: [u8; 32],

    pub relayer_fee_max: u64,

    pub relayer_fee_taken: u64,
}

impl WithdrawArgs {
    pub fn new(
        proof_a: [u8; 64],

        proof_b: [u8; 128],

        proof_c: [u8; 64],

        nullifier_hash: [u8; 32],

        root: [u8; 32],

        withdrawal_commitment: [u8; 32],

        relayer_fee_max: u64,

        relayer_fee_taken: u64,
    ) -> Self {
        Self {
            proof_a,

            proof_b,

            proof_c,

            nullifier_hash,

            root,

            withdrawal_commitment,

            relayer_fee_max,

            relayer_fee_taken,
        }
    }
}

/// Custom struct: WithdrawalEvent
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct WithdrawalEvent {
    pub nullifier_hash: [u8; 32],

    pub recipient: Pubkey,

    pub relayer: Pubkey,

    pub relayer_fee: u64,

    pub treasury_fee: u64,
}

impl WithdrawalEvent {
    pub fn new(
        nullifier_hash: [u8; 32],

        recipient: Pubkey,

        relayer: Pubkey,

        relayer_fee: u64,

        treasury_fee: u64,
    ) -> Self {
        Self {
            nullifier_hash,

            recipient,

            relayer,

            relayer_fee,

            treasury_fee,
        }
    }
}

// ============================================================================
// END OF GENERATED FILE
// ============================================================================
