"use strict";

/**
 * circuits/test/circuits.test.js
 *
 * Cryptographic logic tests for SolnadoCash ZK circuits.
 *
 * Prerequisites (run T06 first):
 *   cd circuits && npm install
 *   npm run compile          # produces build/withdraw_js/, build/deposit_js/, build/*.r1cs
 *   npm run trusted-setup    # (or use test keys — see helpers below)
 *
 * Run:
 *   cd circuits && npm test
 */

const path  = require("path");
const fs    = require("fs");
const snarkjs      = require("snarkjs");
const { buildPoseidon } = require("circomlibjs");

// ── Build artifact paths ──────────────────────────────────────────────────────
const BUILD_DIR = path.join(__dirname, "../build");

const WITHDRAW_WASM = path.join(BUILD_DIR, "withdraw_js/withdraw.wasm");
const WITHDRAW_ZKEY = path.join(BUILD_DIR, "withdraw_final.zkey");
const WITHDRAW_VK   = path.join(BUILD_DIR, "withdraw_vk.json");

const DEPOSIT_WASM  = path.join(BUILD_DIR, "deposit_js/deposit.wasm");
const DEPOSIT_ZKEY  = path.join(BUILD_DIR, "deposit_final.zkey");
const DEPOSIT_VK    = path.join(BUILD_DIR, "deposit_vk.json");

// ── Constants ─────────────────────────────────────────────────────────────────
const TREE_DEPTH    = 20;
const DENOMINATION  = 1_000_000_000n; // 1 SOL in lamports

// ── Check build artifacts exist ───────────────────────────────────────────────
function artifactsExist(wasm, zkey, vk) {
    return fs.existsSync(wasm) && fs.existsSync(zkey) && fs.existsSync(vk);
}

// ── Global Poseidon instance ──────────────────────────────────────────────────
let poseidon;
let F; // finite field helper

beforeAll(async () => {
    poseidon = await buildPoseidon();
    F = poseidon.F;
}, 30_000);

// ── Poseidon helper — returns BigInt ─────────────────────────────────────────
function poseidonHash(...inputs) {
    const result = poseidon(inputs.map(x => F.e(x)));
    return BigInt(F.toObject(result));
}

// ── Random field element (< BN254 scalar field order) ────────────────────────
function randomFieldElement() {
    // BN254 scalar field order
    const p = 21888242871839275222246405745257275088548364400416034343698204186575808495617n;
    // Generate 32 random bytes and reduce mod p
    const bytes = new Uint8Array(32);
    for (let i = 0; i < 32; i++) bytes[i] = Math.floor(Math.random() * 256);
    let value = 0n;
    for (const b of bytes) value = (value << 8n) | BigInt(b);
    return value % p;
}

// ── Incremental Merkle tree (mirrors on-chain logic) ─────────────────────────
// ZEROS[i] = Poseidon(ZEROS[i-1], ZEROS[i-1]), ZEROS[0] = 0
// These must match the on-chain Rust ZEROS constant (generated by scripts/generate_zeros.js).
function buildZeros(depth) {
    const zeros = new Array(depth);
    zeros[0] = 0n;
    for (let i = 1; i < depth; i++) {
        zeros[i] = poseidonHash(zeros[i - 1], zeros[i - 1]);
    }
    return zeros;
}

class IncrementalMerkleTree {
    constructor(depth) {
        this.depth = depth;
        this.zeros = buildZeros(depth);
        this.filledSubtrees = [...this.zeros];
        this.roots = [this._zeroRoot()];
        this.nextIndex = 0n;
    }

    _zeroRoot() {
        let hash = 0n;
        for (let i = 0; i < this.depth; i++) {
            hash = poseidonHash(hash, this.zeros[i]);
        }
        return hash;
    }

    // Insert a leaf and return its Merkle path.
    insert(leaf) {
        let currentHash = BigInt(leaf);
        let currentIndex = this.nextIndex;
        const pathElements = [];
        const pathIndices = [];

        for (let i = 0; i < this.depth; i++) {
            pathIndices.push(Number(currentIndex % 2n));
            if (currentIndex % 2n === 0n) {
                pathElements.push(this.zeros[i]);
                this.filledSubtrees[i] = currentHash;
                currentHash = poseidonHash(currentHash, this.zeros[i]);
            } else {
                pathElements.push(this.filledSubtrees[i]);
                currentHash = poseidonHash(this.filledSubtrees[i], currentHash);
            }
            currentIndex = currentIndex / 2n;
        }

        this.roots.push(currentHash);
        this.nextIndex += 1n;

        return {
            pathElements,
            pathIndices,
            root: currentHash,
            leafIndex: this.nextIndex - 1n,
        };
    }

    currentRoot() {
        return this.roots[this.roots.length - 1];
    }
}

// ── Deposit proof helpers ─────────────────────────────────────────────────────

function generateDepositInputs(denomination = DENOMINATION) {
    const nullifier = randomFieldElement();
    const secret    = randomFieldElement();
    const commitment = poseidonHash(nullifier, secret, denomination);
    return { nullifier, secret, denomination, commitment };
}

async function generateDepositProof(inputs) {
    const { proof, publicSignals } = await snarkjs.groth16.fullProve(
        {
            commitment:   inputs.commitment.toString(),
            denomination: inputs.denomination.toString(),
            nullifier:    inputs.nullifier.toString(),
            secret:       inputs.secret.toString(),
        },
        DEPOSIT_WASM,
        DEPOSIT_ZKEY,
    );
    return { proof, publicSignals };
}

// ── Withdraw proof helpers ────────────────────────────────────────────────────

function generateWithdrawInputs(tree, denomination = DENOMINATION) {
    const nullifier     = randomFieldElement();
    const secret        = randomFieldElement();
    const recipient     = randomFieldElement(); // wallet as field element
    const relayerAddr   = randomFieldElement();
    const relayerFeeMax = 83_000n; // ~0.000083 SOL

    const commitment         = poseidonHash(nullifier, secret, denomination);
    const nullifierHash      = poseidonHash(nullifier);
    const withdrawalCommitment = poseidonHash(relayerAddr, relayerFeeMax, recipient);

    const { pathElements, pathIndices, root } = tree.insert(commitment);

    return {
        // public
        nullifierHash,
        root,
        withdrawalCommitment,
        // private
        nullifier,
        secret,
        denomination,
        pathElements,
        pathIndices,
        recipient,
        relayerAddress: relayerAddr,
        relayerFeeMax,
    };
}

async function generateWithdrawProof(inputs) {
    const circomInputs = {
        nullifierHash:         inputs.nullifierHash.toString(),
        root:                  inputs.root.toString(),
        withdrawalCommitment:  inputs.withdrawalCommitment.toString(),
        nullifier:             inputs.nullifier.toString(),
        secret:                inputs.secret.toString(),
        denomination:          inputs.denomination.toString(),
        pathElements:          inputs.pathElements.map(x => x.toString()),
        pathIndices:           inputs.pathIndices.map(x => x.toString()),
        recipient:             inputs.recipient.toString(),
        relayerAddress:        inputs.relayerAddress.toString(),
        relayerFeeMax:         inputs.relayerFeeMax.toString(),
    };

    const { proof, publicSignals } = await snarkjs.groth16.fullProve(
        circomInputs,
        WITHDRAW_WASM,
        WITHDRAW_ZKEY,
    );
    return { proof, publicSignals };
}

async function verifyWithdraw(proof, publicSignals) {
    const vkey = JSON.parse(fs.readFileSync(WITHDRAW_VK, "utf8"));
    return snarkjs.groth16.verify(vkey, publicSignals, proof);
}

async function verifyDeposit(proof, publicSignals) {
    const vkey = JSON.parse(fs.readFileSync(DEPOSIT_VK, "utf8"));
    return snarkjs.groth16.verify(vkey, publicSignals, proof);
}

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

describe("Deposit circuit", () => {
    const skip = !artifactsExist(DEPOSIT_WASM, DEPOSIT_ZKEY, DEPOSIT_VK);
    const testFn = skip ? test.skip : test;

    if (skip) {
        test("skipped — run `npm run compile` and `bash scripts/trusted_setup.sh` first", () => {});
    }

    testFn("generates a valid proof for a well-formed commitment", async () => {
        const inputs = generateDepositInputs();
        const { proof, publicSignals } = await generateDepositProof(inputs);
        const valid = await verifyDeposit(proof, publicSignals);
        expect(valid).toBe(true);
    }, 60_000);

    testFn("public signals are [commitment, denomination]", async () => {
        const inputs = generateDepositInputs();
        const { publicSignals } = await generateDepositProof(inputs);
        // publicSignals[0] = commitment, publicSignals[1] = denomination
        expect(BigInt(publicSignals[0])).toBe(inputs.commitment);
        expect(BigInt(publicSignals[1])).toBe(inputs.denomination);
    }, 60_000);

    testFn("rejects commitment computed with wrong nullifier", async () => {
        const inputs = generateDepositInputs();
        // Tamper: use a different nullifier to compute commitment but keep original
        const tamperedCommitment = poseidonHash(randomFieldElement(), inputs.secret, inputs.denomination);
        const tamperedInputs = { ...inputs, commitment: tamperedCommitment };
        // snarkjs throws if constraints are unsatisfied
        await expect(generateDepositProof(tamperedInputs)).rejects.toThrow();
    }, 60_000);

    testFn("rejects commitment computed with wrong denomination", async () => {
        const inputs = generateDepositInputs();
        const wrongDenomination = 999_999_999n;
        const tamperedInputs = {
            ...inputs,
            denomination: wrongDenomination,
            commitment: poseidonHash(inputs.nullifier, inputs.secret, wrongDenomination),
        };
        // The public denomination now differs from what was committed — proof must fail
        // OR: the commitment with wrong denomination won't match — fullProve should throw
        await expect(
            snarkjs.groth16.fullProve(
                {
                    commitment:   inputs.commitment.toString(), // original
                    denomination: wrongDenomination.toString(), // mismatch
                    nullifier:    inputs.nullifier.toString(),
                    secret:       inputs.secret.toString(),
                },
                DEPOSIT_WASM,
                DEPOSIT_ZKEY,
            )
        ).rejects.toThrow();
    }, 60_000);
});

describe("Withdraw circuit", () => {
    const skip = !artifactsExist(WITHDRAW_WASM, WITHDRAW_ZKEY, WITHDRAW_VK);
    const testFn = skip ? test.skip : test;
    let tree;

    beforeEach(() => {
        tree = new IncrementalMerkleTree(TREE_DEPTH);
    });

    if (skip) {
        test("skipped — run `npm run compile` and `bash scripts/trusted_setup.sh` first", () => {});
    }

    testFn("generates a valid proof for a deposit in the tree", async () => {
        const inputs = generateWithdrawInputs(tree);
        const { proof, publicSignals } = await generateWithdrawProof(inputs);
        const valid = await verifyWithdraw(proof, publicSignals);
        expect(valid).toBe(true);
    }, 120_000);

    testFn("public signals are [nullifierHash, root, withdrawalCommitment] in this exact order", async () => {
        const inputs = generateWithdrawInputs(tree);
        const { publicSignals } = await generateWithdrawProof(inputs);
        expect(BigInt(publicSignals[0])).toBe(inputs.nullifierHash);
        expect(BigInt(publicSignals[1])).toBe(inputs.root);
        expect(BigInt(publicSignals[2])).toBe(inputs.withdrawalCommitment);
    }, 120_000);

    // ── Bug fix 20 — Recipient malleability ──────────────────────────────────
    // CRITICAL: a relayer must NOT be able to swap the recipient and still get
    // a valid proof. This test verifies the withdrawalCommitment binding works.
    testFn("BF-20: tampered recipient invalidates the proof (relayer cannot steal funds)", async () => {
        const inputs = generateWithdrawInputs(tree);
        const { proof, publicSignals } = await generateWithdrawProof(inputs);

        // Attacker tries to replace recipient with their own address
        const attackerAddress = randomFieldElement();
        const tamperedCommitment = poseidonHash(
            inputs.relayerAddress,
            inputs.relayerFeeMax,
            attackerAddress, // swapped recipient
        );

        // The original proof was generated for the original withdrawalCommitment.
        // Replacing publicSignals[2] with tamperedCommitment must cause verify to return false.
        const tamperedSignals = [
            publicSignals[0], // nullifierHash (unchanged)
            publicSignals[1], // root (unchanged)
            tamperedCommitment.toString(), // withdrawalCommitment with attacker address
        ];

        const valid = await verifyWithdraw(proof, tamperedSignals);
        expect(valid).toBe(false);
    }, 120_000);

    // ── Bug fix 20 — relayerAddress swap also fails ───────────────────────────
    testFn("BF-20: tampered relayerAddress invalidates the proof", async () => {
        const inputs = generateWithdrawInputs(tree);
        const { proof, publicSignals } = await generateWithdrawProof(inputs);

        const maliciousRelayer = randomFieldElement();
        const tamperedCommitment = poseidonHash(
            maliciousRelayer, // swapped relayer
            inputs.relayerFeeMax,
            inputs.recipient,
        );

        const tamperedSignals = [publicSignals[0], publicSignals[1], tamperedCommitment.toString()];
        const valid = await verifyWithdraw(proof, tamperedSignals);
        expect(valid).toBe(false);
    }, 120_000);

    // ── Invalid Merkle path ───────────────────────────────────────────────────
    testFn("rejects proof with wrong Merkle root", async () => {
        const inputs = generateWithdrawInputs(tree);

        // Use a root that doesn't contain the commitment
        const fakeRoot = randomFieldElement();
        const tamperedInputs = { ...inputs, root: fakeRoot };
        await expect(generateWithdrawProof(tamperedInputs)).rejects.toThrow();
    }, 120_000);

    // ── Stale root ────────────────────────────────────────────────────────────
    testFn("proof generated against an older root remains valid if root is in history", async () => {
        // Insert leaf 1 (our deposit)
        const inputs = generateWithdrawInputs(tree);
        // Insert more leaves to advance the root
        for (let i = 0; i < 5; i++) {
            tree.insert(poseidonHash(randomFieldElement(), randomFieldElement(), DENOMINATION));
        }
        // The old root is still in the Merkle path — proof should verify against the old root
        const { proof, publicSignals } = await generateWithdrawProof(inputs);
        const valid = await verifyWithdraw(proof, publicSignals);
        expect(valid).toBe(true);
    }, 120_000);

    // ── Double-spend prevention (nullifier uniqueness) ────────────────────────
    testFn("two withdrawals from the same note produce the same nullifierHash", async () => {
        const inputs = generateWithdrawInputs(tree);
        const { publicSignals: signals1 } = await generateWithdrawProof(inputs);

        // Same note, different recipient (would be a different withdrawal attempt)
        const newRecipient = randomFieldElement();
        const newCommitment = poseidonHash(inputs.relayerAddress, inputs.relayerFeeMax, newRecipient);
        const inputs2 = { ...inputs, recipient: newRecipient, withdrawalCommitment: newCommitment };
        const { publicSignals: signals2 } = await generateWithdrawProof(inputs2);

        // nullifierHash (index 0) must be identical — on-chain checks this to prevent double-spend
        expect(signals1[0]).toBe(signals2[0]);
    }, 120_000);

    // ── Invalid nullifier ─────────────────────────────────────────────────────
    testFn("rejects proof if nullifierHash does not match Poseidon(nullifier)", async () => {
        const inputs = generateWithdrawInputs(tree);
        // Provide a tampered nullifierHash that doesn't match the private nullifier
        const fakeNullifierHash = randomFieldElement();
        const tamperedInputs = { ...inputs, nullifierHash: fakeNullifierHash };
        await expect(generateWithdrawProof(tamperedInputs)).rejects.toThrow();
    }, 120_000);

    // ── Bug fix 12 — denomination is private ─────────────────────────────────
    testFn("BF-12: wrong denomination in private input makes proof fail", async () => {
        const inputs = generateWithdrawInputs(tree);
        // The commitment in the tree was for DENOMINATION.
        // If prover uses a different denomination, commitment won't match the Merkle leaf.
        const wrongDenom = 500_000_000n; // 0.5 SOL
        const tamperedInputs = { ...inputs, denomination: wrongDenom };
        await expect(generateWithdrawProof(tamperedInputs)).rejects.toThrow();
    }, 120_000);
});

describe("Poseidon hash consistency", () => {
    test("nullifier hash is deterministic", () => {
        const nullifier = 12345678901234567890n;
        const h1 = poseidonHash(nullifier);
        const h2 = poseidonHash(nullifier);
        expect(h1).toBe(h2);
    });

    test("commitment is deterministic", () => {
        const nullifier = 111n;
        const secret = 222n;
        const denom = 1_000_000_000n;
        const c1 = poseidonHash(nullifier, secret, denom);
        const c2 = poseidonHash(nullifier, secret, denom);
        expect(c1).toBe(c2);
    });

    test("different inputs produce different hashes", () => {
        expect(poseidonHash(1n)).not.toBe(poseidonHash(2n));
        expect(poseidonHash(1n, 2n)).not.toBe(poseidonHash(2n, 1n));
    });

    test("withdrawalCommitment changes when any of its three fields change", () => {
        const base = poseidonHash(100n, 200n, 300n); // (relayer, feeMax, recipient)
        const swappedRelayer    = poseidonHash(999n, 200n, 300n);
        const swappedFeeMax     = poseidonHash(100n, 999n, 300n);
        const swappedRecipient  = poseidonHash(100n, 200n, 999n);

        expect(base).not.toBe(swappedRelayer);
        expect(base).not.toBe(swappedFeeMax);
        expect(base).not.toBe(swappedRecipient);
    });

    test("incremental Merkle tree produces consistent roots", () => {
        const tree1 = new IncrementalMerkleTree(TREE_DEPTH);
        const tree2 = new IncrementalMerkleTree(TREE_DEPTH);

        const leaf = poseidonHash(111n, 222n, DENOMINATION);
        const path1 = tree1.insert(leaf);
        const path2 = tree2.insert(leaf);

        expect(path1.root).toBe(path2.root);
        expect(path1.pathElements).toEqual(path2.pathElements);
        expect(path1.pathIndices).toEqual(path2.pathIndices);
    });

    test("Merkle path verification is correct", () => {
        const tree = new IncrementalMerkleTree(TREE_DEPTH);
        const leaf = poseidonHash(111n, 222n, DENOMINATION);
        const { pathElements, pathIndices, root } = tree.insert(leaf);

        // Manually walk the path and verify we get the same root
        let current = leaf;
        for (let i = 0; i < TREE_DEPTH; i++) {
            if (pathIndices[i] === 0) {
                current = poseidonHash(current, pathElements[i]);
            } else {
                current = poseidonHash(pathElements[i], current);
            }
        }
        expect(current).toBe(root);
    });
});
