// @vitest-environment node
//
// app/src/cspConfig.test.ts
//
// The production CSP is generated by vite.config.ts from the RPC and relayer origins. It read them
// from `process.env` only, which sees shell variables but not `.env` files, while Vite injects
// `import.meta.env.VITE_*` into the bundle from `.env`/`.env.local` regardless. Configuring the RPC in
// a file, as app/.env.example instructs, therefore put the endpoint in the bundle and left it out of
// `connect-src`: the build succeeded and the deployed app blocked its own RPC calls. The dev server
// never applies this policy, so it only showed up once deployed.
//
// This loads the real config the way `vite build` does, from a scratch directory whose only source of
// the RPC endpoint is an .env file, and reads the policy the build would inject.

import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadConfigFromFile } from 'vite';

const CONFIG = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../vite.config.ts');

async function builtPolicy(envFile: string): Promise<string> {
  const dir = mkdtempSync(path.join(tmpdir(), 'csp-'));
  const cwd = process.cwd();
  try {
    writeFileSync(path.join(dir, '.env.production'), envFile);
    process.chdir(dir);
    const loaded = await loadConfigFromFile({ command: 'build', mode: 'production' }, CONFIG, dir);
    const plugin = (loaded!.config.plugins ?? [])
      .flat()
      .find((p) => p && typeof p === 'object' && 'name' in p && p.name === 'inject-csp') as
      | { transformIndexHtml: (html: string) => string }
      | undefined;
    expect(plugin, 'inject-csp plugin').toBeTruthy();
    const html = plugin!.transformIndexHtml('<html><head></head></html>');
    return html.match(/Content-Security-Policy" content="([^"]+)"/)![1];
  } finally {
    process.chdir(cwd);
    rmSync(dir, { recursive: true, force: true });
  }
}

// vitest loads the app's own .env files into process.env before any test runs, and a shell variable
// deliberately wins over a file, so the developer's local endpoint would mask the file under test.
// Clear every VITE_ key for each test and put them back afterwards.
const SAVED = Object.fromEntries(Object.entries(process.env).filter(([k]) => k.startsWith('VITE_')));

describe('production CSP follows the configured endpoints', () => {
  beforeEach(() => {
    for (const k of Object.keys(SAVED)) delete process.env[k];
  });
  afterEach(() => {
    for (const k of Object.keys(process.env)) if (k.startsWith('VITE_')) delete process.env[k];
    Object.assign(process.env, SAVED);
  });

  it('authorises an RPC endpoint that is configured in an .env file', async () => {
    const policy = await builtPolicy(
      'VITE_RPC_ENDPOINT=https://rpc.example.test/?api-key=x\nVITE_RELAYER_URL=https://relay.example.test\n'
    );
    const connect = policy.split('; ').find((d) => d.startsWith('connect-src'))!;
    expect(connect).toContain('https://rpc.example.test');
    expect(connect).toContain('wss://rpc.example.test');
    expect(connect).toContain('https://relay.example.test');
    expect(connect).not.toContain('api.devnet.solana.com');
  });

  it('a shell variable still wins over the file', async () => {
    process.env.VITE_RPC_ENDPOINT = 'https://shell.example.test';
    const policy = await builtPolicy('VITE_RPC_ENDPOINT=https://file.example.test\n');
    expect(policy).toContain('https://shell.example.test');
    expect(policy).not.toContain('https://file.example.test');
  });
});
