#!/usr/bin/env node
"use strict";

/**
 * scripts/convert_vk_to_rust.js
 *
 * Converts a snarkjs Groth16 verification key JSON into a Rust constant
 * compatible with the `groth16-solana` crate (LightProtocol).
 *
 * Usage:
 *   node scripts/convert_vk_to_rust.js circuits/build/withdraw_vk.json \
 *     > programs/solnadocash/src/vk.rs
 *
 * The groth16-solana Groth16Verifyingkey struct expects:
 *   - vk_alpha_g1:  [u8; 64]   — G1 point (x,y), each 32 bytes big-endian
 *   - vk_beta_g2:  [u8; 128]  — G2 point ((x0,x1),(y0,y1)), each 32 bytes
 *   - vk_gamme_g2: [u8; 128]  — note: typo is in the crate name, preserved here
 *   - vk_delta_g2: [u8; 128]  — G2 point
 *   - vk_ic:       &[[u8;64]] — IC[0..n_public+1] — G1 points
 *
 * snarkjs JSON format uses decimal strings for coordinates.
 * G1 points:  [x, y]           (field elements as decimal strings)
 * G2 points:  [[x0,x1],[y0,y1]] (field elements as decimal strings)
 *
 * See PROJET_enhanced.md Section 12.3 for context.
 */

const fs = require("fs");

const vkPath = process.argv[2];
if (!vkPath) {
    console.error("Usage: node convert_vk_to_rust.js <withdraw_vk.json>");
    process.exit(1);
}

const vk = JSON.parse(fs.readFileSync(vkPath, "utf8"));

// ── Helpers ──────────────────────────────────────────────────────────────────

// Convert a decimal string field element to a 32-byte big-endian Rust array literal.
function fe32(decStr) {
    const n = BigInt(decStr);
    const hex = n.toString(16).padStart(64, "0");
    const bytes = [];
    for (let i = 0; i < 32; i++) {
        bytes.push("0x" + hex.slice(i * 2, i * 2 + 2));
    }
    return `[${bytes.join(", ")}]`;
}

// G1 point [x, y] → [u8; 64]
function g1(point) {
    const x = fe32(point[0]);
    const y = fe32(point[1]);
    // Concatenate: x bytes then y bytes
    const xBytes = point[0];
    const yBytes = point[1];
    // Build as flat 64-byte array
    const n0 = BigInt(point[0]);
    const n1 = BigInt(point[1]);
    const hex0 = n0.toString(16).padStart(64, "0");
    const hex1 = n1.toString(16).padStart(64, "0");
    const bytes = [];
    for (let i = 0; i < 32; i++) bytes.push("0x" + hex0.slice(i * 2, i * 2 + 2));
    for (let i = 0; i < 32; i++) bytes.push("0x" + hex1.slice(i * 2, i * 2 + 2));
    return `[\n        ${bytes.join(", ")}\n    ]`;
}

// G2 point [[x0,x1],[y0,y1]] → [u8; 128]
// snarkjs stores G2 as [[x_re,x_im],[y_re,y_im]] where the coordinates are in Fp2.
// Solana's alt_bn128 precompile uses EIP-197 format: x_im || x_re || y_im || y_re.
function g2(point) {
    const coords = [point[0][1], point[0][0], point[1][1], point[1][0]];
    const bytes = [];
    for (const c of coords) {
        const n = BigInt(c);
        const hex = n.toString(16).padStart(64, "0");
        for (let i = 0; i < 32; i++) bytes.push("0x" + hex.slice(i * 2, i * 2 + 2));
    }
    return `[\n        ${bytes.join(", ")}\n    ]`;
}

// ── Build output ──────────────────────────────────────────────────────────────

const nPublic = vk.nPublic; // number of public inputs

const icEntries = vk.IC.map((pt, i) => {
    return `    // IC[${i}]${i === 0 ? " — constant term" : ` — public input ${i}`}\n    ${g1(pt)}`;
}).join(",\n");

const output = `// programs/solnadocash/src/vk.rs
// GENERATED by scripts/convert_vk_to_rust.js — DO NOT EDIT.
// Groth16 verifying key for the withdraw circuit.
// Public inputs: [nullifierHash, root, withdrawalCommitment] (${nPublic} inputs)
//
// Source: circuits/build/withdraw_vk.json
// Circuit hash (withdraw): see circuits/build/withdraw_final.zkey metadata

use groth16_solana::groth16::Groth16Verifyingkey;

pub const WITHDRAW_VK: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: ${nPublic},

    vk_alpha_g1: ${g1(vk.vk_alpha_1)},

    vk_beta_g2: ${g2(vk.vk_beta_2)},

    // Note: field name "vk_gamme_g2" is a typo in the groth16-solana crate — preserved as-is.
    vk_gamme_g2: ${g2(vk.vk_gamma_2)},

    vk_delta_g2: ${g2(vk.vk_delta_2)},

    vk_ic: &[
${icEntries}
    ],
};
`;

process.stdout.write(output);
