#!/usr/bin/env node
"use strict";

/**
 * scripts/generate_zeros.js
 *
 * Generates the compile-time ZEROS constant for the Anchor program.
 * ZEROS[i] = Poseidon(ZEROS[i-1], ZEROS[i-1]), with ZEROS[0] = 0 (empty leaf).
 *
 * These values must be IDENTICAL to the values used by the off-chain prover.
 * If they differ, all deposits produce wrong roots and all withdrawals fail.
 *
 * Usage:
 *   cd circuits && npm install
 *   node ../scripts/generate_zeros.js
 *
 * Then paste the output into programs/solnadocash/src/zeros.rs.
 * Commit zeros.rs to git — it is a frozen constant, never recomputed at runtime.
 *
 * See PROJET_enhanced.md Section 12.4 for context.
 */

const { buildPoseidon } = require("circomlibjs");

async function main() {
    const poseidon = await buildPoseidon();
    const F = poseidon.F;

    const DEPTH = 20;
    const zeros = [];

    let current = F.zero; // empty leaf = field element zero
    for (let i = 0; i < DEPTH; i++) {
        // Store as 32-byte big-endian Buffer
        const val = F.toObject(current); // BigInt
        const hex = val.toString(16).padStart(64, "0");
        zeros.push(Buffer.from(hex, "hex"));
        current = poseidon([current, current]);
    }

    // Print as Rust constant
    console.log("// programs/solnadocash/src/zeros.rs");
    console.log("// GENERATED by scripts/generate_zeros.js — DO NOT EDIT.");
    console.log("// Poseidon BN254 empty-subtree values (circomlibjs convention).");
    console.log("// ZEROS[0] = field 0 (empty leaf).");
    console.log("// ZEROS[i] = Poseidon(ZEROS[i-1], ZEROS[i-1]).");
    console.log("");
    console.log(`pub const ZEROS: [[u8; 32]; ${DEPTH}] = [`);
    zeros.forEach((z, i) => {
        const bytes = Array.from(z).map(b => `0x${b.toString(16).padStart(2, "0")}`).join(", ");
        console.log(`    [${bytes}], // level ${i}`);
    });
    console.log("];");

    // Also print as hex strings for reference
    console.log("\n// Hex reference (for cross-checking with circomlibjs):");
    zeros.forEach((z, i) => {
        console.log(`// ZEROS[${i}] = 0x${z.toString("hex")}`);
    });
}

main().catch(err => {
    console.error(err);
    process.exit(1);
});
